### ISSUE TITLE
Prepare OpenLab session for OpenStackDays/OpenSourceSummit Tokyo

### ISSUE THREAD

**Issue by oomichi** [oomichi/try-kubernetes#84]
7月18日(木) 14:00 OpenSourceSummit Japan、
7月23日(火) OpenStack Days Tokyo
で発表する OpenLab セッションの準備を行う。

- [x] シナリオ作成
- [x] レビュー
- [x] レビューコメント反映
- [x] Open Source Summit Japan スライド作成
- [x] 英語のシナリオ作成
- [x] OpenStack Days スライド作成
- [x] デモンストレーション、練習

**Comment by oomichi** [comment]
シナリオ作成
--------------

CFPは20分セッションで登録したはずなのに40分セッションで通ってしまった。
ので40分を前提にシナリオを組む。

**Comment by oomichi** [comment]
![assets_-Lgc3odgVkxxnaX3VQr0_-Lgc7_ezWA5WYK8pqYQI_-Lgc7awUJfkqzGXov2US_getting_started-1](https://user-images.githubusercontent.com/1287154/59232939-5001d580-8b9b-11e9-997e-1b92ac6ef992.png)

**Comment by atoato88** [comment]
想定される質問
上のフロー図の中のどこかでgithubとか外部のレポジトリを使うのでしょうか？
それとも全ての作業がopenlabの中で閉じてるのでしょうか？
開発者としては普段使ってる開発スキームから逸脱したくないと思うはずなのでそのあたりが知りたい。
開発者がgithubにPR出したら、自動でテストされるのが理想ですかね。

**Comment by oomichi** [comment]
2. OpenLab概要（10分）
---------------------------

**Comment by oomichi** [comment]
[3] Kubernetes on OpenStack testing（10分）
-------------------------------------------------

**Comment by oomichi** [comment]
[4] E2E and Conformance tests of Kubernetes（10分）
==================================

**Comment by oomichi** [comment]
[5] Summary（3分）
=============

最後に本日のセッションをまとめます。

1. クラウド関連 OSS の組合せテストに興味があれば、OpenLab に参加しましょう
まずはメンバーになることを提案し、その後組合せテストを提案する流れになります。
テストジョブが失敗した際にどのようにコミュニティに働きかけていくのかも検討しておく必要があります。
2. Kubernetes のリソース要求を OpenStack と連携して実現するのが cloud-provider-openstack になります
今後 Cinder/Manila CSI Plugin への開発注力となるため、Cinder/Manila Provisioner を使わずCinder/Manila CSI Plugin を利用するのがお薦め
3. Kubernetes クラスタの構築確認にe2e テストが利用可能
ただし特定のプロバイダ向けや Alpha 機能のテストも含まれるため、Conformance テストから利用することがお薦め

**Comment by atoato88** [comment]
上記 [2] 〜 [5] を確認しました。

# 気になったところ
-   [3] cloud-provider-openstack 概要
    1.   Octavia Ingress Controller：ServiceだとLBと1体1になると書かれてますが、Ingressを使うとそれが防げる？OctaviaのインスタンスはK8Sクラスタ1つに対して１つで、1つのOctaviaインスタンスが複数のIngressリソースの処理を受け持つということですか？
    2.   Barbican KMS Plugin：なんかイメージしづらい文章でした。可能なら図がほしいところですが、ざっくりと「どういう機能が提供されるのか？」をサマライズした日本語にしたほうが理解しやすいと思いました。

-   [5] Summary
    1.   Summaryに対するコメントというより全体に対するコメントなのですが、本セッションのねらいと対象読者、参加者に何を持ち帰ってもらいたいのか？がちょっとわかりませんでした。というのも、最後のSummaryをみると、1. 〜 3. のそれぞれのつながりが感じづらいと思ったからです。
Summaryの 1. 〜 3. それぞれの説明はそれぞれでわかるのですが、このセッションでこれら３つをまとめて取り扱っている意図がもう少し伝わるような説明がほしいと思いました。
あるいは、つながりはあまりなく、[CNDTのセッション説明(JULY 23(TUE) Room F [2F1] 13:20 - 14:00)](https://cloudnativedays.jp/cndt2019/#schedule) に「本セッションではOpenStack/Kubernetes連携の概要、コミュニティでの開発状況などを紹介します。」とあるように、それぞれを紹介するためのセッションということであれば、Summaryの冒頭でその旨を言った上で 1. 〜 3. を述べるのが良いかもしれません。

**Comment by oomichi** [comment]
レビュー、ありがとうございます。

> Octavia Ingress Controller：ServiceだとLBと1体1になると書かれてますが、Ingressを使うとそれが防げる？OctaviaのインスタンスはK8Sクラスタ1つに対して１つで、1つのOctaviaインスタンスが複数のIngressリソースの処理を受け持つということですか？

はい、その通りです。
Kubernetes における Ingress の目的がそもそも外部接続している LB を共有することで、LB のコストを削減することなので、そのLB 部分が OpenStack Octavia で実装される場合も同じ目的になります。
つまり、Ingress による複数の外部接続を Octavia インスタンスで処理することになります。

> Barbican KMS Plugin：なんかイメージしづらい文章でした。可能なら図がほしいところですが、ざっくりと「どういう機能が提供されるのか？」をサマライズした日本語にしたほうが理解しやすいと思いました。

Barbican KMS の内容は README を翻訳しただけのもので、私自身良くわかっていないです。
実は Adisky さんに確認したところ、Barbican KMS の開発は現在アクティブに行われていないことが輪借りました。
https://kubernetes.slack.com/archives/C0LSA3T7C/p1562691866184300?thread_ts=1562641954.159700&cid=C0LSA3T7C

そこで今回のプレゼンテーションからは削除しようと思います。

**Comment by oomichi** [comment]
> Summaryに対するコメントというより全体に対するコメントなのですが、本セッションのねらいと対象読者、参加者に何を持ち帰ってもらいたいのか？がちょっとわかりませんでした。というのも、最後のSummaryをみると、1. 〜 3. のそれぞれのつながりが感じづらいと思ったからです。
Summaryの 1. 〜 3. それぞれの説明はそれぞれでわかるのですが、このセッションでこれら３つをまとめて取り扱っている意図がもう少し伝わるような説明がほしいと思いました。
あるいは、つながりはあまりなく、CNDTのセッション説明(JULY 23(TUE) Room F [2F1] 13:20 - 14:00) に「本セッションではOpenStack/Kubernetes連携の概要、コミュニティでの開発状況などを紹介します。」とあるように、それぞれを紹介するためのセッションということであれば、Summaryの冒頭でその旨を言った上で 1. 〜 3. を述べるのが良いかもしれません。

鋭いご指摘、ありがとうございます。
そうですね、今回なぜこのようなシナリオで話したのか、その前提を先に言ったほうがマトメが理解しやすいかもしれません。
そのような形でシナリオを修正しようと思います。

**Comment by oomichi** [comment]
Open Source Summit Japan 向けスライド作成が完了した。
